import {
    LineEdit,
    VerticalBox,
    HorizontalBox,
    StyleMetrics,
    GridBox,
} from "std-widgets.slint";
import { Styles } from "styles.slint";
import { GroupBox, CheckBox } from "std-widgets.slint";

export global AppState {
    in-out property <int> counter: 42;
    callback partial_effort(string);
}

component InternalText inherits Text {
    overflow: clip;
    //font-size: Styles.font-size;
    //font-family: Styles.font-family;
    vertical-alignment: center;
    horizontal-alignment: center;
    wrap: word-wrap;
}

component MyText inherits Rectangle {
    in property <string> text: "Test";
    in property <color> text_color: #000000;
    in property <int> font-weight: 400;
    in property <color> error_color: #ffffff;
    in property <color> background_color: #ffffff;
    in property <TextHorizontalAlignment> horizontal-alignment: TextHorizontalAlignment.center;

    width: Styles.width;
    min-height: myText.height;
    background: root.error_color;
    clip: true;
    Rectangle {
        background: root.background_color;
        width: parent.width - 5px;
        height: parent.height - 5px;

        innerRect := Rectangle {
            property <length> parent_width: parent.width;
            //height: myText.height;
            width: myText.width;
            property <length> position: (parent.width - self.width) / 2;
            property <length> start_position: (parent.width - self.width) / 2;
            x: position;
            property <bool> running: self.width > parent.width;
            animate x {
                duration: 1000ms;
                easing: ease-in-out;
            }
            Timer {
                interval: 5000ms;
                running: running;

                triggered => {
                    position = position == 0 ? (parent_width - innerRect.width) : 0;
                //debug("myTetx.width: " + myTetx.width / 1px + " - parent_width: " + parent_width / 1px + " - width: " + innerRect.width / 1px);
            }
            }

            myText := InternalText {
                color: root.text_color;
                text: root.text;
                font-weight: root.font-weight;
                horizontal-alignment: root.horizontal-alignment;
            }
        }
    }
}

component Data inherits Rectangle {
    in property <string> text: "70-12-31";
    in property <color> text_color: #000000;

    height: Styles.height;
    width: Styles.width;
    background: #ffffff;

    MyText {
        text: text;
        text_color: text_color;
        background: root.background;
        background_color: root.background;
        error_color: root.background;
    }
}

component PartialEffort inherits Rectangle {
    in property <int> value: 0;
    in property <brush> text_color: #000000;
    in property <int> effort: 0;
    in property <color> background_color;

    height: Styles.height;
    width: Styles.width;

    MyText {
        height: parent.height;
        text: value == 0 ? "" : value;
        text_color: #000000;
        background_color: root.background_color;
        error_color: rgba(255, 0, 0, value >= effort ? 1.0 : value / effort);
        font-weight: 800;
    }
}

component WorkerEffort inherits Rectangle {
    //in property <string> value: "Worker12345|100\nWorker12|100\nWorker1|100\nWorker54321|100\nWorker5|100\nWorker|100\nWorker3|100\nWorker4|100\nWorker6|100\nWorker789|100\nWorker8|100\nWorker9|100";
    in property <string> value: "Worker12345|80\nWorker12|80\nWorker1|80\nWorker54321|80\nWorker5|80\nWorker|80\nWorker3|80\nWorker4|80\nWorker6|80\nWorker789|80\nWorker8|80\nWorker9|80";
    in property <color> text_color: #000000;
    //in property <string> value;
    //in property <string> value: "Worker12345|100";
    //in property <string> value: "Worker12|100";
    //in property <string> value: "Worker1|100";
    //in property <string> value: "Worker54321|100";
    //in property <string> value: "Worker5|100";
    //in property <string> value: "Worker|100";
    //in property <string> value: "Worker3|100";
    //in property <string> value: "Worker4|100";
    //in property <string> value: "Worker6|100";
    //in property <string> value: "Worker789|100";
    //in property <string> value: "Worker8|100";
    //in property <string> value: "Worker9|100";
    //in property <color> text_color: #000000;

    width: Styles.width;

    MyText {
        width: parent.width;
        text: value;
        text_color: text_color;
    }
}

component MyHorizontalBox inherits HorizontalBox {
    spacing: 1px;
    padding: 1px;
}

component MyVerticalBox inherits VerticalBox {
    spacing: 1px;
    padding: 1px;
}

component SingleEffort inherits MyVerticalBox {
    in property <string> worker_efforts;
    in property <int> effort;
    in property <color> background_color;

    property <int> partial_effort_value;

    init => {
        AppState.partial_effort(worker_efforts);
    }

    PartialEffort {
        value: partial_effort_value;
        effort: root.effort;
        background_color: root.background_color;
    }

    WorkerEffort {
        value: worker_efforts;
        background: #ffffff;
    }
}

component EffortByDate inherits MyVerticalBox {
    in property <[string]> worker_efforts;
    in property <[int]> partial_efforts;
    in property <int> effort;
    in property <color> background_color;

    // SingleEffort {
    //     worker_efforts: "";
    //     effort: root.effort;
    //     background_color: root.background_color;
    // }

    MyHorizontalBox {
        for item in partial_efforts: PartialEffort {
            value: item;
            effort: root.effort;
            background_color: root.background_color;
        }
    }

    MyHorizontalBox {
        for item in worker_efforts: WorkerEffort {
            value: item;
            background: #ffffff;
        }
    }
}

struct DevEffort {
    partial_efforts: [int],
    worker_efforts: [string],
    max_height: int,
    effort: int,
    background_color: color,
}

struct PjmDatas {
    project_name: string,
    current_dates: [string],
    current_week: string,
    dev_efforts: [DevEffort]
}

component SingleHeader {
    in property <string> text: "Text";
    in property <TextHorizontalAlignment> horizontal-alignment: TextHorizontalAlignment.center;
    MyText {
        max-height: Styles.height;
        font-weight: 800;
        text: root.text;
        //background: #007dfa78;
        min-width: Styles.width;
        max-width: Styles.width;
        horizontal-alignment: root.horizontal-alignment;
    }
}

component Header inherits Rectangle {
    MyHorizontalBox {
        SingleHeader {
            text: "Project";
        }

        SingleHeader {
            text: "Platform";
        }

        SingleHeader {
            text: "PM";
        }

        SingleHeader {
            text: "Dev";
        }

        SingleHeader {
            text: "Budget";
        }
    }
}

component Worker inherits Rectangle {
    in property <PjmDatas> pjm_datas;
    MyHorizontalBox {
        SingleHeader {
            text: "";
        }

        SingleHeader {
            text: "";
        }

        SingleHeader {
            text: "";
        }

        InternalText {
            width: Styles.width * 2;
            horizontal-alignment: TextHorizontalAlignment.right;
            text: "Worker1\nWorker2\nWorker3\nWorker12345678";
        }
    }
}

component Dates inherits Rectangle {
    in property <PjmDatas> pjm_datas;
    MyHorizontalBox {
        for item in root.pjm_datas.current_dates: Data {
            text: item;
            background: item == root.pjm_datas.current_week ? #ffff00 : #ffffff;
        }
    }
}

component SingleProject inherits Rectangle {
    border-width: 1px;
    border-color: black;
    border-radius: 1px;

    in property <PjmDatas> pjm_datas;
    MyHorizontalBox {
        MyVerticalBox {
            for dev_effort in root.pjm_datas.dev_efforts: EffortByDate {
                MyHorizontalBox {
                    MyText {
                        text: "Project";
                        min-height: dev_effort.max_height * Styles.height;
                    }

                    MyText {
                        text: "Platform";
                        min-height: dev_effort.max_height * Styles.height;
                    }

                    MyText {
                        text: "PM";
                        min-height: dev_effort.max_height * Styles.height;
                    }

                    MyText {
                        text: dev_effort.effort;
                        min-height: dev_effort.max_height * Styles.height;
                    }

                    MyText {
                        text: "Budget";
                        min-height: dev_effort.max_height * Styles.height;
                    }
                }
            }
        }

        Rectangle {
            MyVerticalBox {
                for dev_effort in root.pjm_datas.dev_efforts: effort_by_date := EffortByDate {
                    worker_efforts: dev_effort.worker_efforts;
                    partial_efforts: dev_effort.partial_efforts;
                    effort: dev_effort.effort;
                    background_color: dev_effort.background_color;
                }
            }
        }
    }
}

component Summary inherits Rectangle {
    in property <PjmDatas> pjm_datas;
    border-width: 1px;
    border-color: black;
    border-radius: 1px;

    MyHorizontalBox {
        Worker {
            pjm_datas: root.pjm_datas;
        }

        percents := Dates {
            pjm_datas: root.pjm_datas;
        }
    }
}

component FirstLine inherits Rectangle {
    in property <PjmDatas> pjm_datas;
    MyHorizontalBox {
        Header { }

        Dates {
            pjm_datas: root.pjm_datas;
        }
    }
}

export component MainWindow inherits Window {
    background: #ffffff;
    default-font-size: Styles.font-size;
    default-font-family: Styles.font-family;
    title: "Project Management Effort Tracker App";
    min-width: 1024px;
    //height: 768px;
    resize-border-width: 10px;

    in property <PjmDatas> pjm_datas;

    MyVerticalBox {

        FirstLine {
            pjm_datas: root.pjm_datas;
        }

        SingleProject {
            pjm_datas: root.pjm_datas;
        }

        Summary {
            pjm_datas: root.pjm_datas;
        }
    }
}
